# Generated by Django 5.0.2 on 2024-02-16 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='cellphone',
            field=models.CharField(max_length=20),
        ),
    ]
