# Generated by Django 5.0.2 on 2024-02-16 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_contact_cellphone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutme',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='aboutme',
            name='projects',
        ),
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
        migrations.AddField(
            model_name='project',
            name='about_me',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='portfolio.aboutme'),
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('issued', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('about_me', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='portfolio.aboutme')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=100)),
                ('period', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('about_me', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='portfolio.aboutme')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('about_me', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='portfolio.aboutme')),
            ],
        ),
    ]
