# Generated by Django 5.0.2 on 2024-02-16 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_remove_aboutme_experience_remove_aboutme_projects_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='about_me',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.aboutme'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='about_me',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.aboutme'),
        ),
        migrations.AlterField(
            model_name='project',
            name='about_me',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.aboutme'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='about_me',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.aboutme'),
        ),
    ]
