# Generated by Django 5.0.2 on 2024-02-16 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_alter_certification_about_me_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certification',
            old_name='issued',
            new_name='issuedby',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='about_me',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='about_me',
        ),
        migrations.RemoveField(
            model_name='project',
            name='about_me',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='about_me',
        ),
        migrations.AddField(
            model_name='aboutme',
            name='certifications',
            field=models.ManyToManyField(blank=True, related_name='about_mes', to='portfolio.certification'),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='experiences',
            field=models.ManyToManyField(blank=True, related_name='about_mes', to='portfolio.experience'),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='about_mes', to='portfolio.project'),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='about_mes', to='portfolio.skill'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='name',
            field=models.CharField(max_length=10),
        ),
    ]
